### PR TITLE
fix: subdirectory pull requests from dependabot

### PR DESCRIPTION
**Pull request by JamesKyburz**
When dependabot sends pull requests for subdirectories in a monorepo the current regex matching the versions fails.

Fixed the regex and added a test too.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by JamesKyburz** [comment]
It looks like the latest version `2.2.0` hasn't been pushed to the main branch which has `2.1.0` in package*.json files.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by JamesKyburz** [comment]
should I have included dist or is this done when released?

**Review by zekth — APPROVED** [review]
Lgtm.

We should make an automatic dist generation on release / commit to master.

**Review by mcollina — APPROVED** [review]
lgtm

**Review by simoneb — CHANGES_REQUESTED** [review]
dist folder not upgraded. make sure husky hooks are run please. https://github.com/fastify/github-action-merge-dependabot/blob/main/.husky/pre-commit

**Comment by JamesKyburz** [comment]
> dist folder not updated. make sure husky hooks are run please. https://github.com/fastify/github-action-merge-dependabot/blob/main/.husky/pre-commit

I had a look why the hook wasn't run (I didn't commit with --skip-verify :)) and it's never run, the pre-commit script isn't executable. I will update this pull request with both the dist and chmod +x :)

**Comment by simoneb** [comment]
> > dist folder not updated. make sure husky hooks are run please. https://github.com/fastify/github-action-merge-dependabot/blob/main/.husky/pre-commit
> 
> I had a look why the hook wasn't run (I didn't commit with --skip-verify :)) and it's never run, the pre-commit script isn't executable. I will update this pull request with both the dist and chmod +x :)

Thanks. I've done the last released of this package and it always ran here, I guess something must have gone awry

**Review by simoneb — APPROVED** [review]

**Comment by JamesKyburz** [comment]
updated this pull request to include dist, and made the .husky/pre-commit script executable too.

**Pull request merged**
