### PR TITLE
Specify engines in package.json

### LINKED ISSUE #211: Specify engine
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

It would be useful to specify the minimum node version in the package.json

### PR DESCRIPTION
**Pull request by Uzlopak**
resolves #211 

For some reason my shell always starts with node 12. So the unit tests did not run. this is a minimal change to just specify which node version we need as a minimum.

### CODE REVIEW

**Comment by Uzlopak** [comment]
Well I created an Issue but I have not enough permissions to link the issue to fix the linked issue check.

**Comment by Uzlopak** [comment]
Resolves #211

**Comment by mcollina** [comment]
Why are you just modifying the dist/index.js file?

**Comment by Uzlopak** [comment]
Whoa! No I did not intend to modify the index.js. I just run the tests, maybe they rebuilt the index.js . Idk.

I will provide a new PR without the modified index.js

**Comment by Uzlopak** [comment]
@mcollina 

I tried again and it was the same tainted branch issue.
I think this happens because of the husky commit hook. It is not in my hand to not modify the index.js. Just if I remove the git hook I can avoid the issue. What should I do?

**Comment by simoneb** [comment]
@Uzlopak can you rebase this PR please? I tend to agree that the engines field is not requires though, this code is not supposed to be run on your machine

**Comment by Uzlopak** [comment]
Closing because I dont think i can rebase it.

**Pull request closed without merging**
