### PR TITLE
chore: replace husky with pre-commit ensure dist integrity

### PR DESCRIPTION
**Pull request by Uzlopak**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
@simoneb 

This should avoid the unintentional commit of the dist.

**Review by simoneb — COMMENTED** [review]
Oh but we need the dist to be generated and committed when we do releases!

**Comment by Uzlopak** [comment]
@simoneb 
I added now an integrity check for the dist file.

**Comment by Uzlopak** [comment]
As you can see the workflows for the commit 1a0ff43 failed because the dist file was not what we would expect. In e9fcfec the integrity check passes.

**Comment by simoneb** [comment]
Apologies but I don't see the value in this solution. I like the simplicity of building the action automatically when committing, so that dist is always aligned with the source code.

**Comment by Uzlopak** [comment]
@simoneb 

I understand. I use this type of logic in the actions at my employer. See e.g. 
https://github.com/metro-digital/setup-tools-for-waas

So it results in two things:

1. If a contributor pushes changes, and also changes the dist files, we can trust the modified dist. When @groozin was pushing we asked him to revert that file. But with the integrity check, we could have accepted it without worrying.

2. When we get some PR by dependabot, which does change the dist file, it gets detected and automerge is prevented. We can run build.yml workflow on that dependabot branch and a correct dist is generated. We must then only squash merge manually. Benefit of this is, that we can actually see, if there was relevant changed and make a release. So e.g. if dependabot updates eslint, it will be merged silently. But if it changes @actions/core we see that a PR got not merged automatically and we can see that it effected the dist file. So we should consider a new release.

3. Also we could rebuild the dist by running build.yml targetting main.

**Pull request closed without merging**
