### PR TITLE
chore(gitignore): use latest github ignore template

### PR DESCRIPTION
**Pull request by Fdawgs**
Removed `node_modules` and `package-lock.json` from it, but otherwise still the same.

#### Checklist

- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by simoneb — COMMENTED** [review]
Why this change?

**Comment by Fdawgs** [comment]
> Why this change?

Primarily to stop yarn sneaking in files, for those who use that as their package manager.

**Comment by simoneb** [comment]
> > Why this change?
> 
> Primarily to stop yarn sneaking in files, for those who use that as their package manager.

Yarn is not generating all those files and because this repository contains a package-lock.json file it's not supposed to be used with yarn.

**Comment by Fdawgs** [comment]
> > > Why this change?
> 
> > 
> 
> > Primarily to stop yarn sneaking in files, for those who use that as their package manager.
> 
> 
> 
> Yarn is not generating all those files and because this repository contains a package-lock.json file it's not supposed to be used with yarn.

Fair point

**Pull request closed without merging**
