### PR TITLE
build(dependabot): ignore minor and patch github-actions updates

### PR DESCRIPTION
**Pull request by Fdawgs**
See fastify/fastify#3451

#### Checklist

- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by simoneb — COMMENTED** [review]
I'm not with this change but I thought I'd mention that recently we started releasing other actions we maintain with vX and vX.X tags too and we noticed that dependabot seems to actually apply some logic here. I am not 100% sure of this because I haven't seen a case which confirms this yet, but I wonder if simply using vX in your workflows triggers this mechanism automatically and no changes are required in the dependabot.yml file

**Comment by Fdawgs** [comment]
> I'm not with this change but I thought I'd mention that recently we started releasing other actions we maintain with vX and vX.X tags too and we noticed that dependabot seems to actually apply some logic here. I am not 100% sure of this because I haven't seen a case which confirms this yet, but I wonder if simply using vX in your workflows triggers this mechanism automatically and no changes are required in the dependabot.yml file

I haven't seen this myself yet either.

From my experience, Dependabot doesn't stay on the major version and will try and use minor and hotfix versions for actions, as an example: https://github.com/tjenkinson/gh-action-auto-merge-dependency-updates/pull/165.
However, this was back in March and they may have changed how Dependabot handles this since then.

**Comment by simoneb** [comment]
Let me see if I can look up the examples I saw, even thought it's not exactly the same as I'm suggesting in the previous comment.

**Comment by simoneb** [comment]
Ok here it is. Just a screenshot as it's a private repo, but it gives the idea.

image

In that action we're maintaining we're now publishing all 3 tags at each release: vX, vX.X, v.X.X.X.

In this case we published v2, v2.3, v2.3.0. Our target repo was using v2.2.0 and without any special dependabot configuration, dependabot created the PR to bump to v2.3 instead of v2.3.0. Now I don't know exactly why, but is kinda suggests that dependabot might be applying some logic there, otherwise I would have expected it to bump to the most specific v2.3.0 version.

**Comment by Fdawgs** [comment]
Thanks @simoneb, really interesting to see!

They must have changed something then without documenting it, as this https://github.com/dependabot/dependabot-core/issues/3194 is still open and alive.

**Comment by simoneb** [comment]
Okay I now have confirmation that referencing semver major tags doesn't require any specific dependabot configuration. I can see in multiple repos that we're referencing, e.g., `<action>@v2` and despite the action having minor and patch versions dependabot is not creating any PRs to bump it. Hence, this PR can be closed.

**Pull request closed without merging**
